"""
Generated by Django 2.1.2 on 2018-11-01 08:41
"""
# pylint: disable=invalid-name
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Migration to add "female" field to invite_invite table
    """
    dependencies = [
        ('invite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='female',
            field=models.BooleanField(default=False),
        ),
    ]
