"""
Generated by Django 2.1.2 on 2018-11-01 10:41
"""
# pylint: disable=invalid-name
from django.db import migrations, models


class Migration(migrations.Migration):
    """Add the host to the family"""
    dependencies = [
        ('invite', '0003_auto_20181101_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='host',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
