"""
Generated by Django 2.1.2 on 2018-11-01 13:34
"""
#pylint: disable=invalid-name,R0801

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """Migration to rename invite table to guest table"""
    dependencies = [
        ('invite', '0004_family_host'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Invite',
            new_name='Guest',
        ),
        migrations.AlterField(
            model_name='guest', name='family', field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name='guests',
                to='invite.Family'),
        ),
    ]
