"""
Migration to add gender field to the accompanies

Generated by Django 2.1.2 on 2018-12-24 13:30
"""
# pylint: disable=invalid-name

from django.db import migrations, models


class Migration(migrations.Migration):
    """The migration to be apply"""
    dependencies = [
        ('invite', '0006_auto_20181102_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='accompany',
            name='female',
            field=models.BooleanField(default=False, verbose_name='is a female'),
        ),
    ]
