# Generated by Django 2.1.4 on 2019-01-31 19:52
# pylint: disable=invalid-name
"""
Add the event MailTemplate model
"""
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    """
    Migration to apply
    """
    dependencies = [
        ('invite', '0009_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('subject', models.CharField(max_length=512, verbose_name='subject')),
                ('text', models.TextField(verbose_name='raw content', blank=True)),
                ('html', models.TextField(verbose_name='html content', blank=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                               to='invite.Event')),
            ],
        ),
    ]
