# Generated by Django 2.1.4 on 2019-01-31 19:53
# pylint: disable=invalid-name
"""
Automatically create the event mail templates for all existing events
"""

from django.db import migrations
from .operations import fill_mailtemplate


class Migration(migrations.Migration):
    """
    Migration to apply
    """
    dependencies = [
        ('invite', '0010_mailtemplate'),
    ]

    operations = [
        migrations.RunPython(fill_mailtemplate.code, fill_mailtemplate.reverse_code)
    ]
