# Generated by Django 2.1.5 on 2019-04-14 16:03
# pylint: disable=invalid-name,missing-docstring
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invite', '0011_fill_mailtemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinedDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('document', models.FileField(upload_to='joins')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('mimetype', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='html',
            field=models.TextField(blank=True, verbose_name='html content'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='subject',
            field=models.CharField(blank=True, max_length=512, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='mailtemplate',
            name='text',
            field=models.TextField(blank=True, verbose_name='raw content'),
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='joined_documents',
            field=models.ManyToManyField(blank=True, to='invite.JoinedDocument'),
        ),
    ]
