# Generated by Django 2.1.7 on 2019-04-27 11:26
# pylint: disable=invalid-name,missing-docstring
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invite', '0013_family_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='owners',
            field=models.ManyToManyField(editable=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
